name: Verificacion

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.9", "3.8"]
    steps:
    - uses: actions/setup-python@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check current directory
      run: pwd
    - name: Ver rutas
      run: ls ../..
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        working-directory: ./API_CIFRADO
        pip install pylint
        pip install -r requirements.txt
    - name: Analyzing code
      run: |
        pylint app
    - name: Analyzing the test code with pylint
      run: |
        pylint tests
    - name: Unit testing
      run: |
        python -m unittest discover -s tests

